"""add provider column for nodes

Revision ID: c3643f7b578a
Revises: d69d4dbd5e38
Create Date: 2016-01-22 10:08:38.129516

"""

# revision identifiers, used by Alembic.
revision = 'c3643f7b578a'
down_revision = 'd69d4dbd5e38'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('provider', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'provider')
    ### end Alembic commands ###
