---
- name: add the rabbitmq public key
  apt_key:
    url: "https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey"
    state: present

- name: add the rabbitmq official repo
  apt_repository:
    repo: "deb https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu/ {{ ansible_distribution_release }} main"
    state: present

- name: install rabbitmq-server
  apt:
    name: rabbitmq-server
    state: present
    update_cache: yes

- name: ensure rabbitmq is running and enabled
  service:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: enable web management for rabbit
  command: rabbitmq-plugins enable rabbitmq_management
